Added documentation for generated files
Haivision/srt pull request #1494
Opened 2020-08-20 09:41 UTC by ethouris

2020-08-24 07:08 UTC, ethouris commented on docs/Developers.md
> +logging is turned on.
Ok, still not sure that this sounds clear.

The logging system has two aspects for every log, which is level and FA. Every logging instruction looks more-less like this:
```
LOGC(cclog.Note, log << "Here is the note");
```
where:
`cclog` - the logger variable that defines the FA. Here `cc` means "Congestion Control".
`Note` - the log level, one of: Debug, Note, Warn, Error, Fatal.

By setting the log level, you allow only logs of given level and above to be printed. By seting on/off particular FA, you allow logs only for allowed FA to be printed.

2020-08-24 07:11 UTC, ethouris commented on docs/Developers.md
> +   * Find any `SRT_LOGFA_` symbol to find the place where it should be pasted
It is nowhere. Simply the script, when run without arguments, generates 3 files in their locations as defined, and exceptionally the `srt.inc.h` file is generated in the current directory. This isn't really a file being part of the project, it only contains a **fragment** that should be pasted into the specific location in the `srt.h` file with replacing the previous content. In the current version it should be located in `srt.h` file at line 600.

2020-08-24 08:26 UTC, ethouris commented on docs/Developers.md
> +   * Find any `SRT_LOGFA_` symbol to find the place where it should be pasted
Tell you what. Forget it. I decided to change things here. Now all files will be generated.

2020-08-24 08:27 UTC, ethouris commented on docs/Developers.md
> +logging is turned on.
Your version seems to be clear enough, though. I'll try to add only some more information to this sentence to clarify.

2020-08-24 14:29 UTC, stevomatthews commented on docs/Developers.md
> +logging is turned on.
How about:
"In addition to levels (Debug, Note, Warn, Error, Fatal) the logging system has functional areas (FA) that allow a developer to
selectively turn on only specific types of logs. For example, in this logging instruction:

```LOGC(cclog.Note, log << "Here is the note");```

`cclog` is a logger variable that defines the FA (Congestion Control). And `Note` defines the log level. By setting an FA, you allow logs only for that FA to be printed. By setting the log level, you allow only logs of that level and above to be printed. This is ..."

2020-08-24 15:36 UTC, ethouris commented on docs/Developers.md
> +logging is turned on.
Ok, I've tried to make some common version out of it all. Please re-check.

2020-08-27 13:47 UTC, maxsharabayko requested changes

2020-08-27 13:47 UTC, maxsharabayko commented on docs/Developers.md
> +### 1. Logging functional areas
For consistency with the rest of the document.
```suggestion
### Logging functional areas
```

2020-08-27 13:47 UTC, maxsharabayko commented on docs/Developers.md
> +### 2. Build options
```suggestion
### Build options
```

2020-08-31 08:13 UTC, maxsharabayko approved these changes

2020-08-31 08:13 UTC, merged