[doc] Added and updated description of useful test applications
Haivision/srt pull request #2191
Opened 2021-11-30 16:38 UTC by ethouris

`srt-multiplex.md` - changed to `srt-test-multiplex.md` and updated

Added `srt-test-relay.md`.

2021-12-01 08:31 UTC, maxsharabayko reviewed
The "sample applications" section of the [`docs/README.md`](https://github.com/Haivision/srt/tree/master/docs#sample-applications) also needs an update then.

2021-12-03 14:44 UTC, ethouris commented
Ok, updated, and I also added one more lacking description :)

2021-12-03 15:45 UTC, mbakholdina requested changes
Hi @ethouris, thank you for updating the documentation! A couple of minor comments from me.

2021-12-03 15:45 UTC, mbakholdina commented on docs/README.md
> +## Testing applications
There is no need to create a separate table for these 2 items. Please move everything under "Sample Applications" table and delete the current one.

2021-12-03 15:45 UTC, mbakholdina commented on docs/README.md
> +## Testing applications
Please also change the folder to "apps" with an appropriate link.

2021-12-03 15:45 UTC, mbakholdina commented on docs/apps/srt-test-multiplex.md
> +## srt-test-multiplex
Something is wrong with the level of headings in this document. It should start with "# srt-test-multiplex" and then "## Usage", etc.. Could you please go through the document and update the levels carefully?

2021-12-03 15:45 UTC, mbakholdina commented on docs/apps/srt-test-relay.md
> +## srt-test-relay
Again, the level of heading is incorrect. Please change ## to #.

2021-12-03 15:45 UTC, mbakholdina commented on docs/apps/srt-test-relay.md
> +## srt-test-relay
I've also noticed that in srt-tunnel document the headings formatting is different. Could you please update it to look similar? Plus please change the title from "SRT Tunnel" to "srt-tunnel" for consistency. Thanks!

2021-12-03 16:24 UTC, ethouris commented
Ok, I added fixes, please check again if everything's ok

2021-12-03 16:40 UTC, mbakholdina requested changes
@ethouris , a couple of suggestions.

2021-12-03 16:40 UTC, mbakholdina commented on docs/README.md
> +| [Using the<br /> `srt-test-multiplex` App](apps/srt-test-multiplex.md) | [testing](testing/)   | [srt-test-multiplex.md](apps/srt-test-multiplex.md) | Testing app that allows to send multiple strea
Folder -> `[apps](apps/)` for the last 2 rows of the table.

2021-12-03 16:40 UTC, mbakholdina commented on docs/README.md
> +| [Using the<br /> `srt-test-multiplex` App](apps/srt-test-multiplex.md) | [testing](testing/)   | [srt-test-multiplex.md](apps/srt-test-multiplex.md) | Testing app that allows to send multiple strea
Please add the dots at the end of description sentence for `srt-file-transmit` and the last 2 applications.

2021-12-03 16:40 UTC, mbakholdina commented on docs/apps/srt-tunnel.md
> +# SRT Tunnel
Change to `srt-tunnel` for consistency please.

2021-12-03 16:40 UTC, mbakholdina commented on docs/README.md
> +| [Using the<br /> `srt-test-multiplex` App](apps/srt-test-multiplex.md) | [testing](testing/)   | [srt-test-multiplex.md](apps/srt-test-multiplex.md) | Testing app that allows to send multiple strea
I would also suggest changing "app" to "application" in the description for the last 2 rows of the table.

2021-12-06 14:29 UTC, mbakholdina approved these changes

2021-12-06 14:30 UTC, merged