Fix openssl static linking error
Haivision/srt pull request #2369
Opened 2022-06-11 03:59 UTC by wangyoucao577

- Upgrade `OPENSSL_USE_STATIC_LIBS` as an option to not only affects windows, but also `pkg-config` found openssl;    
- Remove useless `--OPENSSL_USE_STATIC_LIBS=TRUE` in android script since it doesn't have any effects;        

Closes https://github.com/Haivision/srt/issues/1172

2022-06-11 05:41 UTC, wangyoucao577 commented
Both coverage decrease and the Travis CI build fail don't seem to make sense since changes in this PR doesn't change any code and any default behavior. Anyone can help to check it?

2022-06-13 10:13 UTC, maxsharabayko requested changes

2022-06-13 10:13 UTC, maxsharabayko commented on CMakeLists.txt
> +option(OPENSSL_USE_STATIC_LIBS "Use static libraries of openssl, affects `USE_OPENSSL_PC` found openssl or on Windows" OFF)
```suggestion
option(OPENSSL_USE_STATIC_LIBS "Link OpenSSL libraries statically." OFF)
```

2022-06-14 20:15 UTC, maxsharabayko commented on scripts/build-android/mksrt
> ---use-openssl-pc=OFF --OPENSSL_USE_STATIC_LIBS=TRUE \
Ok, merging as is. We can have a follow-up fix later if needed. At least Android CI build is passing.

2022-06-15 07:33 UTC, merged

2022-06-15 07:36 UTC, maxsharabayko commented
@wangyoucao577 
Thank you for this great PR!
I had to squash-merge it into one commit to avoid having 8 commits addressing the same change. But thank you for following the contribution guide and naming those commits properly!