[core] Fix : Sequence number in the ACK packet isn’t correct (#2873)
Haivision/srt pull request #2877
Opened 2024-02-15 02:04 UTC by kura979

2024-02-15 11:45 UTC, maxsharabayko requested changes
The Yoda notation is not used in the project. To be consistent, the typical order should be  used.

2024-02-15 11:45 UTC, maxsharabayko commented on srtcore/list.cpp
> +        if (0 == m_iLength)
```suggestion
        if (m_iLength == 0)
```

2024-02-15 11:45 UTC, maxsharabayko commented on srtcore/list.cpp
> +    if (0 == m_iLength)
```suggestion
    if (m_iLength == 0)
```

2024-02-16 09:33 UTC, maxsharabayko approved these changes

2024-02-16 09:47 UTC, merged

2024-02-19 17:05 UTC, gou4shi1 commented
I think this PR will re-introduce this bug: fix https://github.com/Haivision/srt/issues/2192#issuecomment-983376741

2024-02-19 17:14 UTC, ethouris commented
In #2527 I have provided various improvements for the receiver buffer. In this solution there's also changed the way of taking the sequence number for ACK, which is no longer taken from the loss list, and it's taken exclusively from the receiver buffer (the ACK actually acknowledges the initial contiguous region in the receiver buffer, which is defined directly in this version). Would you be able to take a look at that?

2024-02-19 17:18 UTC, maxsharabayko commented
> `m_iLargestSeq` should record history seq, and should not be reset after empty, to fix concurrent issues.
> 
> We should find another way to fix your issue "the next packet loss seqno has a distance more than m_iSeqNoTH"

Just thinking out loud, what if the `m_iLargestSeq` would be ignored upon inserting to the RCV loss list if the loss list is empty?
As a workaround to resolve both issues until #2527 is merged.

2024-02-20 09:29 UTC, ethouris commented
Yes, #2527 doesn't fix the loss list, it simply takes out one of its roles in deciding about ACK. Loss list in here is exclusively used for recording the loss for the need of NAKREPORT and in case of the file CC, also checking the loss level for speed control.

2024-02-20 10:42 UTC, maxsharabayko commented
@gou4shi1 The bug was that a data packet 899264404 with a gap is inserted into the receiver buffer (899264403 is missing). But before the loss is recorded in the RCV loss list, the TSBPD thread drops the missing packet seqno 899264403.
I am afraid I forgot how does the m_iLargestSeq` fixes the concurrency issue.

The original issue description (https://github.com/Haivision/srt/issues/2192#issuecomment-983376741):
> When processData() received 899264404, it was added into the recv buffer, after recvbuf_acklock was unlocked, the tsbpd thread played 899264404 and dropped 899264403, then processData() immediately insert 899264403 back into loss list, after this, getFirstLostSeq() keep return 899264403

2024-02-20 10:50 UTC, maxsharabayko commented
Please continue the discussion in #2881.